export enum Actions {
   UPDATE_USERINFO = 'UPDATE_USERINFO',
   UPDATE_IS_AUTH = 'UPDATE_IS_AUT',
   UPDATE_SEARCH_GAME = 'GETTING_SEARCH_GAME',
   GETTING_GENRES = 'GETTING_GENRES',
   UPDATE_GAMES_ON_GENRES = "GETTING_GAMES_ON_GENRES"
}